const a = 10


try{

 a = 5

}catch(err){
    console.log(err)
}

console.log("Continuando o c√≥digo")
